# SPDX-License-Identifier: GPL-2.0-only

obj-$(CONFIG_CHARGE_WT6670F)	+= wt6670f_hvdcp30.o
obj-$(CONFIG_CHARGE_BQ2589X)	+= bq2589x_charger.o
obj-$(CONFIG_CHARGE_SGM4151X)	+= sgm4151x_charger.o
obj-$(CONFIG_WT_CHARGER)	+= wt_chg.o
